image:
  registry: "docker.io"
  repository: "kanboard/kanboard"
  tag: "v1.2.35"
  pullPolicy: "IfNotPresent"

application:
  port: 80
  persistence:
    enabled: false
    persistentVolumeClaim:
      name: kanboard-pvc
      create: true
      storageClass: manual
      size: 5Gi
      accessMode: ReadWriteMany
    


nodePort:
  enabled: false
  port: ~

clusterip:
  enabled: false
  port: 8080

ingress:
  enabled: false
  ingressClassName: "nginx"
  host: ~
  tls: ~

securityContext:
  pod: 
    readOnlyRootFilesystem: true
  container: 
    readOnlyRootFilesystem: true

resources: ~
