{{- if .Values.application.persistence.enabled -}}
{{- if .Values.application.persistence.persistentVolumeClaim.create -}}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.application.persistence.persistentVolumeClaim.name }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.application.persistence.persistentVolumeClaim.storageClass }}
  resources:
    requests:
      storage: {{ .Values.application.persistence.persistentVolumeClaim.size }}
{{- end -}}
{{- end -}}
